--Creates tables 

CREATE TABLE CLASSTEMPLATE (
    ClassTemplateId INT IDENTITY PRIMARY KEY,  
    Description NVARCHAR(255) NULL,
    RelatedId INT NOT NULL,         
	CONSTRAINT FK_ClassTemplate_RelatedId FOREIGN KEY (RelatedId) 
		REFERENCES RELATEDTABLE(RelatedId) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE RELATEDTABLE (
    RelatedId INT IDENTITY PRIMARY KEY, 
    RelatedName NVARCHAR(50) UNIQUE NOT NULL,
	Value INT DEFAULT 0 NOT NULL,
CONSTRAINT CK_RelatedTable_Value CHECK (Value BETWEEN 0 AND 100)
);

--Opretter CATEGORY Tabellen
CREATE TABLE CATEGORY (
	CategoriId INT PRIMARY KEY IDENTITY(1,1), 
	CategoryName NVARCHAR(30) 
);
GO
--Opretter PRODUCT Tabellen
CREATE TABLE PRODUCT (
	ProductId INT PRIMARY KEY IDENTITY(1,1),
	ProductName NVARCHAR (50), 
	FOREIGN KEY (CategoryId) REFERENCES CATEGORY(CategoryId) 
);
GO